// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebHoTroHocTap.DataAccess;

#nullable disable

namespace WebHoTroHocTap.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_unicode_ci")
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("WebHoTroHocTap.DataAccess.Entities.Block", b =>
                {
                    b.Property<int>("BlockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("block_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("BlockId"));

                    b.Property<string>("BlockType")
                        .IsRequired()
                        .HasColumnType("enum('TEXT','IMAGE','AUDIO','VIDEO','QUIZ','FLASHCARD')")
                        .HasColumnName("block_type");

                    b.Property<string>("ContentText")
                        .HasColumnType("text")
                        .HasColumnName("content_text");

                    b.Property<string>("MediaUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("media_url");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int")
                        .HasColumnName("order_index");

                    b.Property<int>("PageId")
                        .HasColumnType("int")
                        .HasColumnName("page_id");

                    b.HasKey("BlockId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "PageId" }, "idx_block_page");

                    b.HasIndex(new[] { "BlockType" }, "idx_block_type");

                    b.ToTable("block", (string)null);
                });

            modelBuilder.Entity("WebHoTroHocTap.DataAccess.Entities.Chapter", b =>
                {
                    b.Property<int>("ChapterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("chapter_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ChapterId"));

                    b.Property<string>("AccessType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('PUBLIC','PRIVATE','PROTECTED')")
                        .HasColumnName("access_type")
                        .HasDefaultValueSql("'PUBLIC'");

                    b.Property<int>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("course_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsDraft")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_draft");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int")
                        .HasColumnName("order_index");

                    b.Property<string>("Passcode")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("passcode");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("title");

                    b.HasKey("ChapterId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CourseId" }, "idx_chapter_course");

                    b.ToTable("chapter", (string)null);
                });

            modelBuilder.Entity("WebHoTroHocTap.DataAccess.Entities.Comment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("comment_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CommentId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<int>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("course_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("CommentId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CourseId" }, "idx_comment_course");

                    b.HasIndex(new[] { "UserId" }, "idx_comment_user");

                    b.ToTable("comment", (string)null);
                });

            modelBuilder.Entity("WebHoTroHocTap.DataAccess.Entities.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("course_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CourseId"));

                    b.Property<string>("AccessType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('PUBLIC','PRIVATE','PROTECTED')")
                        .HasColumnName("access_type")
                        .HasDefaultValueSql("'PUBLIC'");

                    b.Property<string>("CoverImage")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("cover_image");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("CreatorId")
                        .HasColumnType("int")
                        .HasColumnName("creator_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Passcode")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("passcode");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('PAUSED','COMPLETED','UPDATING')")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'UPDATING'");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("UpdatedAt"));

                    b.HasKey("CourseId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "AccessType" }, "idx_course_access_type");

                    b.HasIndex(new[] { "CreatorId" }, "idx_course_creator");

                    b.HasIndex(new[] { "Status" }, "idx_course_status");

                    b.ToTable("course", (string)null);
                });

            modelBuilder.Entity("WebHoTroHocTap.DataAccess.Entities.CourseInvitation", b =>
                {
                    b.Property<int>("InvitationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("invitation_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("InvitationId"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("course_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("InviteeEmail")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("invitee_email");

                    b.Property<int?>("InviteeUserId")
                        .HasColumnType("int")
                        .HasColumnName("invitee_user_id");

                    b.Property<int>("InviterId")
                        .HasColumnType("int")
                        .HasColumnName("inviter_id");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("responded_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('PENDING','ACCEPTED','DECLINED')")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'PENDING'");

                    b.HasKey("InvitationId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "InviteeUserId" }, "fk_invitation_invitee");

                    b.HasIndex(new[] { "InviterId" }, "fk_invitation_inviter");

                    b.HasIndex(new[] { "CourseId" }, "idx_invitation_course");

                    b.HasIndex(new[] { "InviteeEmail" }, "idx_invitation_invitee_email");

                    b.HasIndex(new[] { "Status" }, "idx_invitation_status");

                    b.ToTable("course_invitation", (string)null);
                });

            modelBuilder.Entity("WebHoTroHocTap.DataAccess.Entities.CourseTag", b =>
                {
                    b.Property<int>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("course_id");

                    b.Property<int>("TagId")
                        .HasColumnType("int")
                        .HasColumnName("tag_id");

                    b.HasKey("CourseId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("course_tag", (string)null);
                });

            modelBuilder.Entity("WebHoTroHocTap.DataAccess.Entities.Enrollment", b =>
                {
                    b.Property<int>("EnrollmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("enrollment_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("EnrollmentId"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("course_id");

                    b.Property<DateTime>("EnrolledAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("enrolled_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("LastAccessedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("last_accessed_at");

                    b.Property<int?>("LastPageId")
                        .HasColumnType("int")
                        .HasColumnName("last_page_id");

                    b.Property<decimal>("ProgressPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("progress_percent");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('LEARNING','COMPLETED')")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'LEARNING'");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("EnrollmentId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CourseId" }, "idx_enrollment_course");

                    b.HasIndex(new[] { "LastPageId" }, "idx_enrollment_lastpage");

                    b.HasIndex(new[] { "UserId" }, "idx_enrollment_user");

                    b.HasIndex(new[] { "UserId", "CourseId" }, "uq_enrollment_user_course")
                        .IsUnique();

                    b.ToTable("enrollment", (string)null);
                });

            modelBuilder.Entity("WebHoTroHocTap.DataAccess.Entities.Flashcard", b =>
                {
                    b.Property<int>("FlashcardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("flashcard_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("FlashcardId"));

                    b.Property<string>("BackText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("back_text");

                    b.Property<int>("FlashcardSetId")
                        .HasColumnType("int")
                        .HasColumnName("flashcard_set_id");

                    b.Property<string>("FrontText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("front_text");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int")
                        .HasColumnName("order_index");

                    b.HasKey("FlashcardId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "FlashcardSetId" }, "idx_flashcard_set");

                    b.ToTable("flashcard", (string)null);
                });

            modelBuilder.Entity("WebHoTroHocTap.DataAccess.Entities.FlashcardSet", b =>
                {
                    b.Property<int>("FlashcardSetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("flashcard_set_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("FlashcardSetId"));

                    b.Property<int>("BlockId")
                        .HasColumnType("int")
                        .HasColumnName("block_id");

                    b.HasKey("FlashcardSetId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "BlockId" }, "uq_flashcardset_block")
                        .IsUnique();

                    b.ToTable("flashcard_set", (string)null);
                });

            modelBuilder.Entity("WebHoTroHocTap.DataAccess.Entities.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("notification_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsRead")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_read");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("enum('NEW_CHAPTER','NEW_COMMENT','NEW_ENROLLMENT','COURSE_INVITATION','INVITATION_ACCEPTED')")
                        .HasColumnName("type");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("NotificationId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IsRead" }, "idx_notification_isread");

                    b.HasIndex(new[] { "UserId" }, "idx_notification_user");

                    b.ToTable("notification", (string)null);
                });

            modelBuilder.Entity("WebHoTroHocTap.DataAccess.Entities.Page", b =>
                {
                    b.Property<int>("PageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("page_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PageId"));

                    b.Property<int>("ChapterId")
                        .HasColumnType("int")
                        .HasColumnName("chapter_id");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int")
                        .HasColumnName("order_index");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("title");

                    b.HasKey("PageId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ChapterId" }, "idx_page_chapter");

                    b.ToTable("page", (string)null);
                });

            modelBuilder.Entity("WebHoTroHocTap.DataAccess.Entities.PageProgress", b =>
                {
                    b.Property<int>("ProgressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("progress_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ProgressId"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("completed_at");

                    b.Property<int>("EnrollmentId")
                        .HasColumnType("int")
                        .HasColumnName("enrollment_id");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_completed");

                    b.Property<int>("PageId")
                        .HasColumnType("int")
                        .HasColumnName("page_id");

                    b.HasKey("ProgressId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "EnrollmentId" }, "idx_progress_enrollment");

                    b.HasIndex(new[] { "PageId" }, "idx_progress_page");

                    b.HasIndex(new[] { "EnrollmentId", "PageId" }, "uq_progress_enrollment_page")
                        .IsUnique();

                    b.ToTable("page_progress", (string)null);
                });

            modelBuilder.Entity("WebHoTroHocTap.DataAccess.Entities.Quiz", b =>
                {
                    b.Property<int>("QuizId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("quiz_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("QuizId"));

                    b.Property<int>("BlockId")
                        .HasColumnType("int")
                        .HasColumnName("block_id");

                    b.HasKey("QuizId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "BlockId" }, "uq_quiz_block")
                        .IsUnique();

                    b.ToTable("quiz", (string)null);
                });

            modelBuilder.Entity("WebHoTroHocTap.DataAccess.Entities.QuizOption", b =>
                {
                    b.Property<int>("OptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("option_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("OptionId"));

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_correct");

                    b.Property<string>("OptionText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("option_text");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int")
                        .HasColumnName("question_id");

                    b.HasKey("OptionId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "QuestionId" }, "idx_option_question");

                    b.ToTable("quiz_option", (string)null);
                });

            modelBuilder.Entity("WebHoTroHocTap.DataAccess.Entities.QuizQuestion", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("question_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("QuestionId"));

                    b.Property<string>("Explanation")
                        .HasColumnType("text")
                        .HasColumnName("explanation");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int")
                        .HasColumnName("order_index");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question_text");

                    b.Property<int>("QuizId")
                        .HasColumnType("int")
                        .HasColumnName("quiz_id");

                    b.HasKey("QuestionId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "QuizId" }, "idx_question_quiz");

                    b.ToTable("quiz_question", (string)null);
                });

            modelBuilder.Entity("WebHoTroHocTap.DataAccess.Entities.RefreshToken", b =>
                {
                    b.Property<int>("TokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("token_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TokenId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DeviceInfo")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("device_info");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime")
                        .HasColumnName("expires_at");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("token_hash");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("TokenId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ExpiresAt" }, "idx_refreshtoken_expiry");

                    b.HasIndex(new[] { "UserId" }, "idx_refreshtoken_user");

                    b.HasIndex(new[] { "TokenHash" }, "uq_refresh_token_hash")
                        .IsUnique();

                    b.ToTable("refresh_token", (string)null);
                });

            modelBuilder.Entity("WebHoTroHocTap.DataAccess.Entities.Tag", b =>
                {
                    b.Property<int>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("tag_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TagId"));

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("tag_name");

                    b.HasKey("TagId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "TagName" }, "uq_tag_name")
                        .IsUnique();

                    b.ToTable("tag", (string)null);
                });

            modelBuilder.Entity("WebHoTroHocTap.DataAccess.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("avatar_url");

                    b.Property<string>("Bio")
                        .HasColumnType("text")
                        .HasColumnName("bio");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active")
                        .HasDefaultValueSql("'1'");

                    b.Property<bool>("NotificationEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("notification_enabled")
                        .HasDefaultValueSql("'1'");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("ThemeMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('LIGHT','DARK')")
                        .HasColumnName("theme_mode")
                        .HasDefaultValueSql("'LIGHT'");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("UpdatedAt"));

                    b.HasKey("UserId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Email" }, "uq_user_email")
                        .IsUnique();

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("WebHoTroHocTap.DataAccess.Entities.Block", b =>
                {
                    b.HasOne("WebHoTroHocTap.DataAccess.Entities.Page", "Page")
                        .WithMany("Blocks")
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_block_page");

                    b.Navigation("Page");
                });

            modelBuilder.Entity("WebHoTroHocTap.DataAccess.Entities.Chapter", b =>
                {
                    b.HasOne("WebHoTroHocTap.DataAccess.Entities.Course", "Course")
                        .WithMany("Chapters")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chapter_course");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("WebHoTroHocTap.DataAccess.Entities.Comment", b =>
                {
                    b.HasOne("WebHoTroHocTap.DataAccess.Entities.Course", "Course")
                        .WithMany("Comments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comment_course");

                    b.HasOne("WebHoTroHocTap.DataAccess.Entities.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comment_user");

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebHoTroHocTap.DataAccess.Entities.Course", b =>
                {
                    b.HasOne("WebHoTroHocTap.DataAccess.Entities.User", "Creator")
                        .WithMany("Courses")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_course_creator");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("WebHoTroHocTap.DataAccess.Entities.CourseInvitation", b =>
                {
                    b.HasOne("WebHoTroHocTap.DataAccess.Entities.Course", "Course")
                        .WithMany("CourseInvitations")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_invitation_course");

                    b.HasOne("WebHoTroHocTap.DataAccess.Entities.User", "InviteeUser")
                        .WithMany("CourseInvitationInviteeUsers")
                        .HasForeignKey("InviteeUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_invitation_invitee");

                    b.HasOne("WebHoTroHocTap.DataAccess.Entities.User", "Inviter")
                        .WithMany("CourseInvitationInviters")
                        .HasForeignKey("InviterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_invitation_inviter");

                    b.Navigation("Course");

                    b.Navigation("InviteeUser");

                    b.Navigation("Inviter");
                });

            modelBuilder.Entity("WebHoTroHocTap.DataAccess.Entities.CourseTag", b =>
                {
                    b.HasOne("WebHoTroHocTap.DataAccess.Entities.Course", "Course")
                        .WithMany("CourseTags")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_coursetag_course");

                    b.HasOne("WebHoTroHocTap.DataAccess.Entities.Tag", "Tag")
                        .WithMany("CourseTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_coursetag_tag");

                    b.Navigation("Course");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("WebHoTroHocTap.DataAccess.Entities.Enrollment", b =>
                {
                    b.HasOne("WebHoTroHocTap.DataAccess.Entities.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_enrollment_course");

                    b.HasOne("WebHoTroHocTap.DataAccess.Entities.Page", "LastPage")
                        .WithMany("Enrollments")
                        .HasForeignKey("LastPageId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_enrollment_lastpage");

                    b.HasOne("WebHoTroHocTap.DataAccess.Entities.User", "User")
                        .WithMany("Enrollments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_enrollment_user");

                    b.Navigation("Course");

                    b.Navigation("LastPage");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebHoTroHocTap.DataAccess.Entities.Flashcard", b =>
                {
                    b.HasOne("WebHoTroHocTap.DataAccess.Entities.FlashcardSet", "FlashcardSet")
                        .WithMany("Flashcards")
                        .HasForeignKey("FlashcardSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_flashcard_set");

                    b.Navigation("FlashcardSet");
                });

            modelBuilder.Entity("WebHoTroHocTap.DataAccess.Entities.FlashcardSet", b =>
                {
                    b.HasOne("WebHoTroHocTap.DataAccess.Entities.Block", "Block")
                        .WithOne("FlashcardSet")
                        .HasForeignKey("WebHoTroHocTap.DataAccess.Entities.FlashcardSet", "BlockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_flashcardset_block");

                    b.Navigation("Block");
                });

            modelBuilder.Entity("WebHoTroHocTap.DataAccess.Entities.Notification", b =>
                {
                    b.HasOne("WebHoTroHocTap.DataAccess.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notification_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebHoTroHocTap.DataAccess.Entities.Page", b =>
                {
                    b.HasOne("WebHoTroHocTap.DataAccess.Entities.Chapter", "Chapter")
                        .WithMany("Pages")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_page_chapter");

                    b.Navigation("Chapter");
                });

            modelBuilder.Entity("WebHoTroHocTap.DataAccess.Entities.PageProgress", b =>
                {
                    b.HasOne("WebHoTroHocTap.DataAccess.Entities.Enrollment", "Enrollment")
                        .WithMany("PageProgresses")
                        .HasForeignKey("EnrollmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_progress_enrollment");

                    b.HasOne("WebHoTroHocTap.DataAccess.Entities.Page", "Page")
                        .WithMany("PageProgresses")
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_progress_page");

                    b.Navigation("Enrollment");

                    b.Navigation("Page");
                });

            modelBuilder.Entity("WebHoTroHocTap.DataAccess.Entities.Quiz", b =>
                {
                    b.HasOne("WebHoTroHocTap.DataAccess.Entities.Block", "Block")
                        .WithOne("Quiz")
                        .HasForeignKey("WebHoTroHocTap.DataAccess.Entities.Quiz", "BlockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_quiz_block");

                    b.Navigation("Block");
                });

            modelBuilder.Entity("WebHoTroHocTap.DataAccess.Entities.QuizOption", b =>
                {
                    b.HasOne("WebHoTroHocTap.DataAccess.Entities.QuizQuestion", "Question")
                        .WithMany("QuizOptions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_option_question");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("WebHoTroHocTap.DataAccess.Entities.QuizQuestion", b =>
                {
                    b.HasOne("WebHoTroHocTap.DataAccess.Entities.Quiz", "Quiz")
                        .WithMany("QuizQuestions")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_question_quiz");

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("WebHoTroHocTap.DataAccess.Entities.RefreshToken", b =>
                {
                    b.HasOne("WebHoTroHocTap.DataAccess.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refreshtoken_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebHoTroHocTap.DataAccess.Entities.Block", b =>
                {
                    b.Navigation("FlashcardSet");

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("WebHoTroHocTap.DataAccess.Entities.Chapter", b =>
                {
                    b.Navigation("Pages");
                });

            modelBuilder.Entity("WebHoTroHocTap.DataAccess.Entities.Course", b =>
                {
                    b.Navigation("Chapters");

                    b.Navigation("Comments");

                    b.Navigation("CourseInvitations");

                    b.Navigation("CourseTags");

                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("WebHoTroHocTap.DataAccess.Entities.Enrollment", b =>
                {
                    b.Navigation("PageProgresses");
                });

            modelBuilder.Entity("WebHoTroHocTap.DataAccess.Entities.FlashcardSet", b =>
                {
                    b.Navigation("Flashcards");
                });

            modelBuilder.Entity("WebHoTroHocTap.DataAccess.Entities.Page", b =>
                {
                    b.Navigation("Blocks");

                    b.Navigation("Enrollments");

                    b.Navigation("PageProgresses");
                });

            modelBuilder.Entity("WebHoTroHocTap.DataAccess.Entities.Quiz", b =>
                {
                    b.Navigation("QuizQuestions");
                });

            modelBuilder.Entity("WebHoTroHocTap.DataAccess.Entities.QuizQuestion", b =>
                {
                    b.Navigation("QuizOptions");
                });

            modelBuilder.Entity("WebHoTroHocTap.DataAccess.Entities.Tag", b =>
                {
                    b.Navigation("CourseTags");
                });

            modelBuilder.Entity("WebHoTroHocTap.DataAccess.Entities.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("CourseInvitationInviteeUsers");

                    b.Navigation("CourseInvitationInviters");

                    b.Navigation("Courses");

                    b.Navigation("Enrollments");

                    b.Navigation("Notifications");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
